Repository TylerMetz/Saucier720, pull requests merged in 2023-03, with the labels that each got.

#141 PantryHTML Updates
  Saucier720-app/src/app/pantry/pantry.component.html
  Saucier720-app/src/app/pantry/pantry.component.scss
Labels: Frontend, Sprint 2

#146 Pantry HTML
  Saucier720-app/src/app/pantry/pantry.component.html
  Saucier720-app/src/app/pantry/pantry.component.scss
Labels: enhancement, Frontend, Sprint 2

#151 Html Tests
  Saucier720-app/src/app/testing/pantry/pantry.component.spec.cy.ts
Labels: Tyler, Frontend, Sprint 2

#171 Update GitIgnore and GitModules
  .gitignore
  .gitmodules
Labels: bug, Tyler, Backend, Sprint 3

#177 Backend Bash Test File
  goTest.sh
Labels: enhancement, Tyler, Backend, Sprint 3

#190 New Bash Script to Run both Frontend and Backend in Parallel
  build.sh
  go.sh
  serve.sh
Labels: enhancement, Frontend, Backend

#192 Deals Page Update
  Saucier720-app/src/app/core/services/deals/deals.service.ts
  Saucier720-app/src/app/deals/deals.component.html
  Saucier720-app/src/app/deals/deals.component.ts
  Saucier720-app/src/app/testing/deals/deals.service.spec.ts
  src/MealDealz.db
  src/main.go
Labels: Frontend, Sprint 3

#194 Deals Page BootStrap Update
  Saucier720-app/src/app/app.module.ts
  Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.html
  Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.scss
  Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.spec.ts
  Saucier720-app/src/app/deals/FEC/deals-table/deals-table.component.ts
  Saucier720-app/src/app/deals/deals.component.html
  Saucier720-app/src/app/deals/deals.component.ts
Labels: enhancement, Frontend, Sprint 3

#195 Pantry Bootstrap Update
  Saucier720-app/src/app/app.module.ts
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.scss
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.spec.ts
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
  Saucier720-app/src/app/pantry/pantry.component.html
  Saucier720-app/src/app/pantry/pantry.component.ts
Labels: enhancement, Frontend, Sprint 3

#196 Login Page Button
  Saucier720-app/src/app/app-routing.module.ts
  Saucier720-app/src/app/app.component.html
  Saucier720-app/src/app/app.component.scss
Labels: enhancement, Frontend, Sprint 3

#204 Post New Pantry Item
  Saucier720-app/src/app/app.module.ts
  Saucier720-app/src/app/core/services/pantry/pantry.service.ts
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.html
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.scss
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.spec.ts
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
  Saucier720-app/src/app/pantry/pantry.component.html
  go.sh
  src/BackendPkg/Router.go
  src/main.go
Labels: Frontend, Backend, Sprint 3

#208 Post to Database from Frontend
  Saucier720-app/src/app/core/services/pantry/pantry.service.ts
  Saucier720-app/src/app/mocks/pantry.mock.ts
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
  src/BackendPkg/Database.go
  src/BackendPkg/Router.go
  src/main.go
Labels: Frontend, Backend, Sprint 3

#219 Sprint3
  Other/BackendFrontendCommunication/HowToRun.md
  Other/BackendFrontendCommunication/HowToRunSprint3.md
  Sprint3Assignment/Sprint3.md
Labels: documentation
