Repository TylerMetz/Saucier720, pull requests merged in 2023-04, with the labels that each got.

#237 Remove karma and jasmine
  Saucier720-app/karma.conf.js
  Saucier720-app/package-lock.json
Labels: enhancement, Frontend

#240 Removed deprecated packaged
  Saucier720-app/package-lock.json
  Saucier720-app/package.json
Labels: enhancement, Frontend

#243 User login setup for Frontend
  Saucier720-app/src/app/app-routing.module.ts
  Saucier720-app/src/app/core/services/Auth/auth.guard.service.spec.ts
  Saucier720-app/src/app/core/services/Auth/auth.guard.service.ts
  Saucier720-app/src/app/core/services/Auth/auth.service.spec.ts
  Saucier720-app/src/app/core/services/Auth/auth.service.ts
  Saucier720-app/src/app/login/login.component.ts
Labels: Frontend, Sprint 4

#266 Frontend new pantry item
  MealDealz.db
  Saucier720-app/src/app/core/services/Auth/auth.service.ts
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.html
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.ts
Labels: Frontend, Sprint 4

#274 Login page cookies
  Saucier720-app/package-lock.json
  Saucier720-app/package.json
  Saucier720-app/src/app/core/services/Auth/auth.service.ts
  Saucier720-app/src/app/core/services/pantry/pantry.service.ts
  Saucier720-app/src/app/login/login.component.ts
Labels: Frontend

#277 Button Organization
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.html
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
  Saucier720-app/src/app/pantry/pantry.component.html
  Saucier720-app/src/app/pantry/pantry.component.scss
Labels: Sprint 4

#288 Recipes Page data
  Saucier720-app/src/app/app.module.ts
  Saucier720-app/src/app/core/interfaces/recipe.ts
  Saucier720-app/src/app/core/services/recipes/recipe.service.ts
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.scss
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
  Saucier720-app/src/app/recipes/recipes.component.html
  Saucier720-app/src/app/testing/core/services/recipe.service.spec.cy.ts
  Saucier720-app/src/app/testing/recipes/recipe-card.component.spec.cy.ts
Labels: Tyler, Sprint 4

#295 Recipe Page Displays Title of Each
  Saucier720-app/src/app/core/interfaces/recipe.ts
  Saucier720-app/src/app/core/services/Auth/auth.service.ts
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
Labels: Frontend, Sprint 4

#307 Signup form flex
  Saucier720-app/src/app/login/FEC/login-form/login-form.component.scss
  Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.html
  Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.scss
  Saucier720-app/src/app/signup/signup.component.html
  Saucier720-app/src/app/signup/signup.component.scss
  Saucier720-app/src/app/testing/login-form.component.spec.cy.ts
Labels: enhancement, Frontend

#308 Login form sets the cookie
  Saucier720-app/src/app/core/services/Auth/auth.service.ts
  Saucier720-app/src/app/login/FEC/login-form/login-form.component.ts
  src/BackendPkg/Router.go
Labels: Frontend, Sprint 4

#311 Recipe instructions
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.scss
Labels: Frontend, Sprint 4

#312 Update pantry with buttons!
  Saucier720-app/src/app/core/services/pantry/pantry.service.ts
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
  Saucier720-app/src/app/pantry/pantry.component.html
  Saucier720-app/src/app/pantry/pantry.component.scss
Labels: Frontend, Sprint 4

#317 Delete pantry item
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.ts
Labels: Frontend, Sprint 4

#350 e2e tests
  Saucier720-app/cypress/e2e/HttpRequests/pantry.http.spec.cy.ts
  Saucier720-app/cypress/support/commands.ts
  Saucier720-app/src/app/core/services/Auth/auth.service.ts
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.scss
Labels: Frontend, Sprint 4

#351 Testing Functionality
  Saucier720-app/cypress/e2e/HttpRequests/deals.http.spec.cy.ts
  Saucier720-app/cypress/e2e/HttpRequests/pantry.http.spec.cy.ts
  Saucier720-app/cypress/e2e/HttpRequests/recipes.http.spec.cy.ts
  Saucier720-app/cypress/e2e/HttpRequests/signup.http.spec.cy.ts
  Saucier720-app/package-lock.json
  Saucier720-app/package.json
  Saucier720-app/src/app/core/services/recipes/recipe.service.ts
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.ts
  Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.html
  Saucier720-app/src/app/signup/signup.component.ts
  Sprint4TestVideos/DealsTest.mov
  Sprint4TestVideos/PantryTests.mov
  Sprint4TestVideos/RecipesTest.mov
Labels: Frontend, Sprint 4

#352 Sam Updates
  Saucier720-app/src/app/app.component.scss
  Saucier720-app/src/app/login/FEC/login-form/login-form.component.scss
  Saucier720-app/src/app/pantry/FEC/new-pantry-item-button/new-pantry-item-button.component.scss
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.html
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.scss
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.scss
  Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.html
  Saucier720-app/src/app/signup/FEC/signup-form/signup-form.component.scss
  Saucier720-app/src/styles.scss
Labels: Frontend, Sprint 4

#359 Recipe cards displaying user info
  Saucier720-app/src/app/core/interfaces/recipe.ts
  Saucier720-app/src/app/pantry/FEC/pantry-table/pantry-table.component.scss
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.html
  Saucier720-app/src/app/recipes/FEC/recipe-card/recipe-card.component.scss
  Saucier720-app/src/styles.scss
Labels: Frontend
